# fly.toml app configuration file generated for slack-bot-so on 2023-10-10T19:22:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "slack-bot-so"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  NEW_QUESTION_CHECK_INTERVAL_SECONDS = "5"
  PORT = "8080"
  QUESTION_QUERY_TIME_PERIOD_MINUTES = "60"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
