// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: bots.sql

package db

import (
	"context"
	"time"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (id, created_at, last_activity_at, bot_token)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, last_activity_at, bot_token
`

type CreateBotParams struct {
	ID             string
	CreatedAt      time.Time
	LastActivityAt time.Time
	BotToken       string
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRowContext(ctx, createBot,
		arg.ID,
		arg.CreatedAt,
		arg.LastActivityAt,
		arg.BotToken,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.BotToken,
	)
	return i, err
}
