// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: tag_subscriptions.sql

package db

import (
	"context"
)

const bindTag = `-- name: BindTag :one
INSERT INTO tag_subscriptions (tag_id, channel_id)
VALUES ($1, $2)
RETURNING tag_id, channel_id
`

type BindTagParams struct {
	TagID     int32
	ChannelID string
}

func (q *Queries) BindTag(ctx context.Context, arg BindTagParams) (TagSubscription, error) {
	row := q.db.QueryRowContext(ctx, bindTag, arg.TagID, arg.ChannelID)
	var i TagSubscription
	err := row.Scan(&i.TagID, &i.ChannelID)
	return i, err
}
