// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: tags.sql

package db

import (
	"context"
	"time"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (tag_name, created_at, channel_id)
VALUES ($1, $2, $3)
RETURNING tag_name, created_at, channel_id
`

type CreateTagParams struct {
	TagName   string
	CreatedAt time.Time
	ChannelID string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.TagName, arg.CreatedAt, arg.ChannelID)
	var i Tag
	err := row.Scan(&i.TagName, &i.CreatedAt, &i.ChannelID)
	return i, err
}
