// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: workspaces.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, workspace_name, workspace_domain, bot_id, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_name, workspace_domain, bot_id, created_at
`

type CreateWorkspaceParams struct {
	ID              string
	WorkspaceName   sql.NullString
	WorkspaceDomain sql.NullString
	BotID           int32
	CreatedAt       time.Time
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.WorkspaceName,
		arg.WorkspaceDomain,
		arg.BotID,
		arg.CreatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.WorkspaceDomain,
		&i.BotID,
		&i.CreatedAt,
	)
	return i, err
}
