// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: workspaces.sql

package db

import (
	"context"
	"time"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, workspace_name, workspace_domain, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_name, workspace_domain, created_at
`

type CreateWorkspaceParams struct {
	ID              string
	WorkspaceName   string
	WorkspaceDomain string
	CreatedAt       time.Time
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.WorkspaceName,
		arg.WorkspaceDomain,
		arg.CreatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.WorkspaceName,
		&i.WorkspaceDomain,
		&i.CreatedAt,
	)
	return i, err
}
